path: '/hhome/ps2g07/document_analysis/github/Project_Synthesis2-/Nil/yolo_dir/synthetic2_data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')


names:
  0: 'signature'
  1: 'stamp'
  2: 'qr'
  3: 'barcode'

